// Proto file: defines gRPC messages and services
// Sercices = our class/interface for remote procedural calls; we group all related gRPC endpoints here
// Messages = structured data type; used for defining requests/responses

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: service-definition.proto

package go_source

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TextExtractionService_ExtractText_FullMethodName = "/pdfservice.TextExtractionService/ExtractText"
)

// TextExtractionServiceClient is the client API for TextExtractionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TextExtractionServiceClient interface {
	// define rpc endpoint called ExtractText
	// this will be a unary rpc
	// request type must be ExtractTextRequest, and return type will be ExtractTextResponse
	ExtractText(ctx context.Context, in *ExtractTextRequest, opts ...grpc.CallOption) (*ExtractTextResponse, error)
}

type textExtractionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTextExtractionServiceClient(cc grpc.ClientConnInterface) TextExtractionServiceClient {
	return &textExtractionServiceClient{cc}
}

func (c *textExtractionServiceClient) ExtractText(ctx context.Context, in *ExtractTextRequest, opts ...grpc.CallOption) (*ExtractTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtractTextResponse)
	err := c.cc.Invoke(ctx, TextExtractionService_ExtractText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TextExtractionServiceServer is the server API for TextExtractionService service.
// All implementations must embed UnimplementedTextExtractionServiceServer
// for forward compatibility.
type TextExtractionServiceServer interface {
	// define rpc endpoint called ExtractText
	// this will be a unary rpc
	// request type must be ExtractTextRequest, and return type will be ExtractTextResponse
	ExtractText(context.Context, *ExtractTextRequest) (*ExtractTextResponse, error)
	mustEmbedUnimplementedTextExtractionServiceServer()
}

// UnimplementedTextExtractionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTextExtractionServiceServer struct{}

func (UnimplementedTextExtractionServiceServer) ExtractText(context.Context, *ExtractTextRequest) (*ExtractTextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExtractText not implemented")
}
func (UnimplementedTextExtractionServiceServer) mustEmbedUnimplementedTextExtractionServiceServer() {}
func (UnimplementedTextExtractionServiceServer) testEmbeddedByValue()                               {}

// UnsafeTextExtractionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TextExtractionServiceServer will
// result in compilation errors.
type UnsafeTextExtractionServiceServer interface {
	mustEmbedUnimplementedTextExtractionServiceServer()
}

func RegisterTextExtractionServiceServer(s grpc.ServiceRegistrar, srv TextExtractionServiceServer) {
	// If the following call pancis, it indicates UnimplementedTextExtractionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TextExtractionService_ServiceDesc, srv)
}

func _TextExtractionService_ExtractText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtractTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextExtractionServiceServer).ExtractText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TextExtractionService_ExtractText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextExtractionServiceServer).ExtractText(ctx, req.(*ExtractTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TextExtractionService_ServiceDesc is the grpc.ServiceDesc for TextExtractionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TextExtractionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pdfservice.TextExtractionService",
	HandlerType: (*TextExtractionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExtractText",
			Handler:    _TextExtractionService_ExtractText_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service-definition.proto",
}
