# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service-definition.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service-definition.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18service-definition.proto\x12\x03pdf\"$\n\x12\x45xtractTextRequest\x12\x0e\n\x06s3_url\x18\x01 \x01(\t\"-\n\x13\x45xtractTextResponse\x12\x16\n\x0e\x65xtracted_text\x18\x01 \x01(\t2Y\n\x15TextExtractionService\x12@\n\x0b\x45xtractText\x12\x17.pdf.ExtractTextRequest\x1a\x18.pdf.ExtractTextResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_definition_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXTRACTTEXTREQUEST']._serialized_start=33
  _globals['_EXTRACTTEXTREQUEST']._serialized_end=69
  _globals['_EXTRACTTEXTRESPONSE']._serialized_start=71
  _globals['_EXTRACTTEXTRESPONSE']._serialized_end=116
  _globals['_TEXTEXTRACTIONSERVICE']._serialized_start=118
  _globals['_TEXTEXTRACTIONSERVICE']._serialized_end=207
# @@protoc_insertion_point(module_scope)
